name: passwordreminder
description: Reminds passwords so that you don't forget the ones that you saved the login for.

publish_to: 'none' 

version: 0.1.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_local_notifications: ^1.4.4+4
  get_it: ^4.0.4
  password: ^1.0.0
  shared_preferences: ^0.5.10
  provider: ^4.3.2+1
  url_launcher: ^5.5.0
  sqflite: ^1.3.1
  passwordfield: ^0.0.82
  battery_optimization: ^0.1.0
  autostart: ^0.0.1
  fluttertoast: ^7.0.4
  local_auth: ^0.6.3+1
  flutter_phoenix: "^0.1.0"
  loading_overlay: ^0.2.1
  multi_select_item: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5


flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "fastlane/metadata/android/en-US/images/icon.png"

flutter:
  uses-material-design: true